name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  - devel

pr: none

pool:
  name: "Azure Pipelines"
  vmImage: "windows-latest"

variables:
  - name: projectName
    value: "apsys.heartbeat"
  - name: buildConfiguration
    value: "Debug"

jobs:
  - job: BuildSolution
    displayName: Build and test solution
    steps:
      - checkout: self
        fetchDepth: 0
      - task: DotNetCoreCLI@2
        displayName: "Restore packages"
        inputs:
          command: "restore"
          projects: "${{parameters.baseFolder}}${{parameters.projectName}}.sln"
          feedsToUse: "config"
          nugetConfigPath: "${{parameters.baseFolder}}NuGet.Config"
      - task: DotNetCoreCLI@2
        displayName: "Build solution"
        inputs:
          projects: "${{parameters.baseFolder}}${{parameters.projectName}}.sln"
          arguments: "--configuration ${{parameters.buildConfiguration}}"
          