name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  - master

pr: none

pool:
  name: "Azure Pipelines"
  vmImage: "windows-latest"

variables:
  - name: projectName
    value: "apsys.heartbeat"
  - name: buildConfiguration
    value: "Release"

extends:
  template: base-pipeline.yml
  parameters:
    projectName: $(projectName)
    buildConfiguration: $(buildConfiguration)
