name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  - devel

pr: none

pool:
  name: "Azure Pipelines"
  vmImage: "windows-latest"

variables:
  - name: projectName
    value: "apsys.heartbeat"
  - name: buildConfiguration
    value: "Debug"

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarqube'
    organization: 'apsys-dev'
    scannerMode: 'MSBuild'
    projectKey: 'apsys-dev_apsys-heartbeat'
    projectName: 'apsys-heartbeat'

- task: SonarCloudAnalyze@1
  inputs:
    jdkversion: 'JAVA_HOME_11_X64'

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

extends:
  template: base-pipeline.yml
  parameters:
    projectName: $(projectName)
    buildConfiguration: $(buildConfiguration)
