parameters:
  - name: projectName
    type: string
  - name: baseFolder
    type: string
    default: "src/"
  - name: buildConfiguration
    type: string
    default: Debug

jobs:
  - job: BuildSolution
    displayName: Build and test solution
    steps:
      - template: build-solution.yml
        parameters:
          projectName: "${{parameters.projectName}}"
          baseFolder: "${{parameters.baseFolder}}"
          buildConfiguration: "${{parameters.buildConfiguration}}"
