parameters:
  - name: projectName
    type: string
  - name: baseFolder
    type: string
    default: "src/"
  - name: buildConfiguration
    type: string
    default: Debug

jobs:
  - job: BuildSolution
    displayName: Build and test solution
    steps:
      - checkout: self
        fetchDepth: 0
      - template: build-solution.yml
        parameters:
          projectName: "${{parameters.projectName}}"
          baseFolder: "${{parameters.baseFolder}}"
          buildConfiguration: "${{parameters.buildConfiguration}}"
      - task: SonarCloudPrepare@1
        inputs:
          SonarCloud: 'sonarqube'
          organization: 'apsys-dev'
          scannerMode: 'MSBuild'
          projectKey: 'apsys-dev_apsys-heartbeat'
          projectName: 'apsys-heartbeat'
      - task: SonarCloudAnalyze@1
        inputs:
          jdkversion: 'JAVA_HOME_11_X64'
      - task: SonarCloudPublish@1
        inputs:
          pollingTimeoutSec: '300'