name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  - master

pr: none

pool:
  name: "Azure Pipelines"
  vmImage: "windows-latest"

variables:
  - group: project-variables-group
  - name: projectName
    value: "apsys.heartbeat"
  - name: buildConfiguration
    value: "Release"
  - name: baseFolder
    value: "src/"
  - name: packageSuffix
    value: ""
  - name: octopusSpaceName
    value: "apsys-mx"

stages:
  - stage: Build
    displayName: Build and run static and dynamic tests
    jobs:

      - job: PackPushArtifacts
        displayName: Pack and push artifacts
        #dependsOn: 'BuildTestSolution'
        steps:
        - template: pack-push-artifact.yml
          parameters:
            buildConfiguration: $(buildConfiguration)
            projectName: "$(projectName).webapi"
            nuGetTitle: "$(projectName) webpi package"
            nuGetDescription: "Package of the $(projectName) webapi project"
            packageSuffix: $(packageSuffix)
            octopusSpaceName: $(octopusSpaceName)
            baseFolder: $(baseFolder)
